### ISSUE TITLE
firewall enabled (even in accept mode) is not compatible with docker

### ISSUE THREAD

**Issue by munhitsu** [ministryofjustice/firewall-formula#15]
As firewall formula forces firewall state and docker alters firewall there is an incopatibility betweeen these two.

A soulution would be to rewrite firewall formula only to alter the firewall, not force apply some snapshot of it.
Each firewall salt state would modify the firewall and create specific file in i.e. /etc/iptables.d/rule-name
At boot time rules will be applied in random order.
Docker when booted would alter firewall accordingly.

**Comment by mattmb** [comment]
closed by #16
