### ISSUE TITLE
when executing single sls file including firewall, host firewall is overwritten with subset

### ISSUE THREAD

**Issue by munhitsu** [ministryofjustice/firewall-formula#7]
Firewall formula stores all firewall metadata in accumulator and rebuilds firewall configuration from scratch. It's a very good approach when we use state.highstate.

Sometimes it's way faster to only execute a single sls. If such sls includes firewall formula than server will update with minimalistic firewall configuration. In worst case we can cut ourselves out.

as salt way is to allow to run specific sls files independently - we need other solution

**Comment by ashb** [comment]
Closed by #16.
